# .gitpod.yml

tasks:
  - init: |
      sdk install java 21.0.4-tem
      sdk default java 21.0.4-tem
      
      # 2. 메이븐 빌드 실행
      ./mvnw install -DskipTests=true
    command: |
      # 3. 설정된 자바 버전 확인 (로그에 표시됨)
      java -version
