# sensor/docker-compose.yml

services:
  sensor:
    # 현재 폴더(sensor)에 있는 Dockerfile을 사용하여 이미지를 빌드합니다.
    build: .
    container_name: sensor_server
    restart: always
    ports:
      # Python 코드가 5000번 포트를 사용하므로, 5000번 포트를 열어줍니다.
      - "5000:5000"
    
    # Python 코드에서 사용할 환경 변수를 설정합니다.
    environment:
      # DB 호스트는 다른 docker-compose의 DB 컨테이너 이름(mysql_db_container)을 사용합니다.
      DB_HOST: 'mysql_db_container' 
      DB_USER: 'root'
      DB_PASSWORD: 'asdf'
      DB_NAME: 'my_app_db'
      
    # DB 서비스와 동일한 공유 네트워크를 사용하도록 설정합니다.
    networks:
      - my-shared-network

# 사용할 네트워크가 외부에서 생성된 것임을 정의합니다.
networks:
  my-shared-network:
    external: true